In [1]:
import pandas
from datascience import *
import numpy as np

Matplotlib is building the font cache; this may take a moment.

In [10]:
winedata = Table.read_table('data/wine_price_vs_blind_quality.csv')
datadic = Table.read_table('data/data_dictionary (2).csv')
#getting the orginal table read

winedata.show(10)
datadic.show()

In [17]:

Q1_table = winedata.select('wine_id','true_quality', 'blind_rating')
Q1_table

wine_id   | true_quality | blind_rating
WIN000000 | 79.6         | 85.4
WIN000001 | 78.8         | 79.4
WIN000002 | 80.8         | 83.5
WIN000003 | 85.5         | 85.1
WIN000004 | 76           | 74.4
WIN000005 | 89.3         | 89.2
WIN000006 | 80.3         | 80.6
WIN000007 | 88.9         | 89.7
WIN000008 | 80.4         | 79.1
WIN000009 | 83           | 80.8
... (39990 rows omitted)